services:
  postgres:
    image: postgres:14
    platform: linux/arm64
    container_name: adverts_pg
    environment:
      - POSTGRES_USER=orestklymko
      - POSTGRES_PASSWORD=orestklymko
      - POSTGRES_DB=adverts
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
