version: '3.0'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: orest_klymko
      POSTGRES_PASSWORD: orest_klymko
      POSTGRES_DB: orest_klymko
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orest_klymko"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
