CREATE TABLE IF NOT EXISTS CITY
(
    ID        BIGSERIAL PRIMARY KEY,
    CITY_NAME VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS DISTRICTS
(
    ID            BIGSERIAL PRIMARY KEY,
    DISTRICT_NAME VARCHAR NOT NULL,
    CITY_ID       BIGINT      NOT NULL,
    FOREIGN KEY (CITY_ID) REFERENCES CITY (ID)
);

CREATE TABLE IF NOT EXISTS DISTRICT_PART
(
    ID            BIGSERIAL PRIMARY KEY,
    DISTRICT_NAME VARCHAR NOT NULL,
    DISTRICT_ID   BIGINT      NOT NULL,
    FOREIGN KEY (DISTRICT_ID) REFERENCES DISTRICTS (ID)
);

CREATE TABLE IF NOT EXISTS STREET
(
    ID            BIGSERIAL PRIMARY KEY,
    STREET_NAME   VARCHAR NOT NULL,
    STREET_NUMBER INTEGER,
    DISTRICT_ID   BIGINT      NOT NULL,
    FOREIGN KEY (DISTRICT_ID) REFERENCES DISTRICTS (ID)
);

CREATE TABLE IF NOT EXISTS ADDRESS
(
    ID              BIGSERIAL PRIMARY KEY,
    BUILD_MAP_TILER BIGINT  NOT NULL,
    DISTRICT_ID     BIGINT NOT NULL,
    STREET_ID       BIGINT NOT NULL,
    CITY_ID         BIGINT NOT NULL,
    LATITUDE        FLOAT   NOT NULL,
    LONGITUDE       FLOAT   NOT NULL,
    FOREIGN KEY (DISTRICT_ID) REFERENCES DISTRICTS(ID),
    FOREIGN KEY (STREET_ID) REFERENCES STREET(ID),
    FOREIGN KEY (CITY_ID) REFERENCES CITY(ID)
);

CREATE TABLE IF NOT EXISTS AGENCY
(
    ID             BIGSERIAL PRIMARY KEY,
    AGENCY_NAME    VARCHAR(255) NOT NULL,
    AGENCY_CATALOG VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS SELLER
(
    ID           BIGSERIAL PRIMARY KEY,
    NAME_OWNER   VARCHAR(255) NOT NULL,
    TYPE_OWNER   VARCHAR(255) NOT NULL,
    NUMBER_PHONE VARCHAR(255) NOT NULL,
    AGENCY_ID    BIGINT,
    FOREIGN KEY (AGENCY_ID) REFERENCES AGENCY (ID)
);

CREATE TABLE IF NOT EXISTS FEATURES
(
    ID      BIGSERIAL PRIMARY KEY,
    FEATURE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROPERTY_BUILDING
(
    ID           BIGSERIAL PRIMARY KEY,
    SQUARE       FLOAT   NOT NULL,
    FLOOR        INTEGER NOT NULL,
    ROOM         INTEGER NOT NULL,
    REALTY_PRICE INTEGER NOT NULL,
    ENERGY_PRICE INTEGER NOT NULL,
    TOTAL_PRICE  INTEGER NOT NULL,
    WITH_PETS    VARCHAR(10) NOT NULL CHECK (WITH_PETS IN ('YES', 'NO', 'UNDEFINED')),
    WITH_KIDS    VARCHAR(10) NOT NULL CHECK (WITH_KIDS IN ('YES', 'NO', 'UNDEFINED'))
);

CREATE TABLE IF NOT EXISTS PROPERTY_FEATURES
(
    PROPERTY_ID BIGINT  NOT NULL,
    FEATURE_ID  BIGINT NOT NULL,
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY_BUILDING (ID),
    FOREIGN KEY (FEATURE_ID) REFERENCES FEATURES (ID)
);

CREATE TABLE IF NOT EXISTS ADVERTS
(
    ID           BIGSERIAL PRIMARY KEY,
    TYPE_REALTY  VARCHAR(255)   NOT NULL,
    PUBLISHED_AT TIMESTAMP NOT NULL,
    EDITED_AT    TIMESTAMP NOT NULL,
    DESCRIPTION  VARCHAR(255)   NOT NULL,
    FINAL_URL    VARCHAR(255)   NOT NULL,
    STATUS       VARCHAR(20)   NOT NULL CHECK (STATUS IN ('IN_USE', 'ARCHIVED', 'NOT_APPROVED')),
    PROPERTY_ID  BIGINT    NOT NULL,
    ADDRESS_ID   BIGINT    NOT NULL,
    SELLER_ID    BIGINT    NOT NULL,
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID),
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY_BUILDING (ID),
    FOREIGN KEY (SELLER_ID) REFERENCES SELLER (ID)
);

CREATE TABLE IF NOT EXISTS ADVANTAGES
(
    ID        BIGSERIAL PRIMARY KEY,
    ADVANTAGE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROPERTY_ADVANTAGES
(
    PROPERTY_ID  BIGINT  NOT NULL,
    ADVANTAGE_ID BIGINT NOT NULL,
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY_BUILDING (ID),
    FOREIGN KEY (ADVANTAGE_ID) REFERENCES ADVANTAGES (ID)
);

CREATE TABLE IF NOT EXISTS IMAGES
(
    ID BIGSERIAL PRIMARY KEY,
    ADVERT_ID BIGINT  NOT NULL,
    IMAGE_URL VARCHAR(255) NOT NULL,
    FOREIGN KEY (ADVERT_ID) REFERENCES ADVERTS (ID)
);

CREATE INDEX idx_street_district_id ON STREET (DISTRICT_ID);
CREATE INDEX idx_city_id ON DISTRICTS (CITY_ID);
CREATE INDEX idx_address_district_id ON ADDRESS (DISTRICT_ID);
CREATE INDEX idx_address_city_id ON ADDRESS (CITY_ID);
CREATE INDEX idx_district_id ON DISTRICT_PART (DISTRICT_ID);
CREATE INDEX idx_address_street_id ON ADDRESS (STREET_ID);
