CREATE TABLE IF NOT EXISTS ADDRESS
(
    ID              BIGSERIAL PRIMARY KEY,
    BUILD_MAP_TILER BIGINT  NOT NULL,
    DISTRICT        VARCHAR NOT NULL,
    ADDRESS_NAME    VARCHAR NOT NULL,
    CITY            VARCHAR NOT NULL,
    LATITUDE        FLOAT   NOT NULL,
    LONGITUDE       FLOAT   NOT NULL
);

CREATE TABLE IF NOT EXISTS AGENCY
(
    ID             BIGSERIAL PRIMARY KEY,
    AGENCY_NAME    VARCHAR NOT NULL,
    AGENCY_CATALOG VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS SELLER
(
    ID           BIGSERIAL PRIMARY KEY,
    NAME_OWNER   VARCHAR NOT NULL,
    TYPE_OWNER   VARCHAR NOT NULL,
    NUMBER_PHONE VARCHAR NOT NULL,
    AGENCY_ID    BIGINT,
    FOREIGN KEY (AGENCY_ID) REFERENCES AGENCY (ID)
);


CREATE TABLE IF NOT EXISTS PROPERTY_BUILDING
(
    ID           BIGSERIAL PRIMARY KEY,
    SQUARE       FLOAT   NOT NULL,
    FLOOR        INTEGER NOT NULL,
    ROOM         INTEGER NOT NULL,
    REALTY_PRICE INTEGER NOT NULL,
    ENERGY_PRICE INTEGER NOT NULL,
    TOTAL_PRICE  INTEGER NOT NULL,
    WITH_PETS    VARCHAR NOT NULL CHECK (WITH_PETS IN ('YES', 'NO', 'UNDEFINED')),
    WITH_KIDS    VARCHAR NOT NULL CHECK (WITH_KIDS IN ('YES', 'NO', 'UNDEFINED'))
);

CREATE TABLE IF NOT EXISTS ADVERTS
(
    ID           BIGSERIAL PRIMARY KEY,
    TYPE_REALTY  VARCHAR   NOT NULL,
    PUBLISHED_AT TIMESTAMP NOT NULL,
    EDITED_AT    TIMESTAMP NOT NULL,
    DESCRIPTION  VARCHAR   NOT NULL,
    FINAL_URL    VARCHAR   NOT NULL,
    STATUS       VARCHAR   NOT NULL CHECK (STATUS IN ('IN_USE', 'ARCHIVED', 'NOT_APPROVED')),
    PROPERTY_ID  BIGINT    NOT NULL,
    ADDRESS_ID   BIGINT    NOT NULL,
    SELLER_ID    BIGINT    NOT NULL,
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID),
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY_BUILDING (ID),
    FOREIGN KEY (SELLER_ID) REFERENCES SELLER (ID)
);


CREATE TABLE IF NOT EXISTS FEATURES
(
    ID          SERIAL PRIMARY KEY,
    PROPERTY_ID BIGINT,
    FEATURE     VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS ADVANTAGES
(
    ID          SERIAL PRIMARY KEY,
    PROPERTY_ID BIGINT ,
    ADVANTAGE   VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS IMAGES
(
    ADVERT_ID BIGINT  NOT NULL,
    IMAGE_URL VARCHAR NOT NULL
);
