INSERT INTO FEATURES (FEATURE) VALUES ('BALCONY');
INSERT INTO FEATURES (FEATURE) VALUES ('AVAILABLE_IMMEDIATELY');
INSERT INTO FEATURES (FEATURE) VALUES ('PARKING');
INSERT INTO FEATURES (FEATURE) VALUES ('ELEVATOR');
INSERT INTO FEATURES (FEATURE) VALUES ('GARAGE');
INSERT INTO FEATURES (FEATURE) VALUES ('BASEMENT');
INSERT INTO FEATURES (FEATURE) VALUES ('WITH_REPAIR');
INSERT INTO FEATURES (FEATURE) VALUES ('WITHOUT_REPAIR');
INSERT INTO FEATURES (FEATURE) VALUES ('WITH_FURNITURE');
INSERT INTO FEATURES (FEATURE) VALUES ('WITHOUT_FURNITURE');
INSERT INTO FEATURES (FEATURE) VALUES ('INTERNET');
INSERT INTO FEATURES (FEATURE) VALUES ('TELEVISION');
INSERT INTO FEATURES (FEATURE) VALUES ('AIR_CONDITIONER');
INSERT INTO FEATURES (FEATURE) VALUES ('REFRIGERATOR');
INSERT INTO FEATURES (FEATURE) VALUES ('DISHWASHER');
INSERT INTO FEATURES (FEATURE) VALUES ('WASHING_MACHINE');


INSERT INTO ADVANTAGES (ADVANTAGE) VALUES ('NEWBUILDING');
INSERT INTO ADVANTAGES (ADVANTAGE) VALUES ('WITH_PETS');
INSERT INTO ADVANTAGES (ADVANTAGE) VALUES ('WITH_CHILD');
INSERT INTO ADVANTAGES (ADVANTAGE) VALUES ('CLOSE_SUPERMARKET');
INSERT INTO ADVANTAGES (ADVANTAGE) VALUES ('CLOSE_BUS_STOP');
INSERT INTO ADVANTAGES (ADVANTAGE) VALUES ('CLOSE_TRAIN_STOP');
INSERT INTO ADVANTAGES (ADVANTAGE) VALUES ('GOOD_TRANSPORT_STATE');
INSERT INTO ADVANTAGES (ADVANTAGE) VALUES ('CENTER');
INSERT INTO ADVANTAGES (ADVANTAGE) VALUES ('OUT_OF_CITY');
INSERT INTO ADVANTAGES (ADVANTAGE) VALUES ('SILENT_DISTRICT');
