CREATE TABLE IF NOT EXISTS REVIEWS
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

INSERT INTO REVIEWS(NAME) VALUES ('Нерухомість не існує');
INSERT INTO REVIEWS(NAME) VALUES ('Нерухомість не відповідає опису');
INSERT INTO REVIEWS(NAME) VALUES ('Власник не відповідає');

CREATE TABLE IF NOT EXISTS REVIEWS_ADVERTS
(
    ADVERT_ID BIGSERIAL NOT NULL,
    REVIEW_ID BIGSERIAL NOT NULL,
    FOREIGN KEY (ADVERT_ID) REFERENCES ADVERTS (ID),
    FOREIGN KEY (REVIEW_ID) REFERENCES REVIEWS (ID)
);

CREATE INDEX review_advert_id ON REVIEWS_ADVERTS(ADVERT_ID);
CREATE INDEX review_review_id ON REVIEWS_ADVERTS(REVIEW_ID)